title: NEWTYPE
description: |
  Another NEWTYPE-themed Jekyll Site
theme: jekyll-theme-newtype
base_url: ""
url: "http://127.0.0.1"
social_links:
  -
    url: https://twitter.com/newkozlukov
    ico: /assets/social-twitter.png
  -
    url: https://github.com/newkozlukov
    ico: /assets/social-github.svg
