title: NEWTYPE
description: |
  Another NEWTYPE-themed Jekyll Site
theme: jekyll-theme-newtype
base_url: http://localhost:4000/
social_links:
  -
    url: https://twitter.com/newkozlukov
    pic: /assets/social-twitter.png
  -
    url: https://github.com/newkozlukov
    pic: /assets/social-github.svg
